### ISSUE TITLE
Funktion wird nicht gefunden für IliValidator Task

### ISSUE THREAD

**Issue by Saela** [sogis/gretl#164]
Wenn das Beispiel in https://github.com/sogis/gretl/blob/master/docs/user/index.md#kleines-beispiel zur Validierung eines Ili-Files ausgeführt wird, dann wird folgender Fehler geworfen:

```
java.lang.ClassNotFoundException: ch.geowerkstatt.ilivalidator.extensions.functions.IsInsideExternalDatasetIoxPlugin
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader.findClass(VisitableURLClassLoader.java:187)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at ch.so.agi.gretl.tasks.IliValidator.validate(IliValidator.java:68)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
Wir benutzen die Version 0.1.10-SNAPSHOT von Geowerkstatt. Die Funktion IsInsideExternalDatasetIoxPlugin wird im IliValidator.java verwendet. Mittels Reflection wird dort etwas ausgeführt:

```
    userFunctionList.add("ch.geowerkstatt.ilivalidator.extensions.functions.IsInsideExternalDatasetResourceIoxPlugin");
    [......]
    for (String userFunction : userFunctionList) {
                Class clazz = Class.forName(userFunction);

```

Offenbar war IsInsideExternalDatasetIoxPlugin noch verfügbar in Version 0.1.9: https://github.com/GeoWerkstatt/geow-interlis-functions/tree/v0.1.9/src/main/java/ch/geowerkstatt/ilivalidator/extensions/functions.

In Version 0.1.10-SNAPSHOT ist die Funktion nicht mehr Verfügbar: https://github.com/GeoWerkstatt/geow-interlis-functions/tree/v0.1.10-SNAPSHOT-8068574593/src/main/java/ch/geowerkstatt/ilivalidator/extensions/functions 

Wir sollten prüfen ob es die Funktion überhaupt benötigt oder ob wir diese weglassen könnten.

**Comment by edigonzales** [comment]
@Saela Diese Kombi sollte funktionieren:

https://github.com/sogis/gretl/blob/V2_4_x/gretl/src/main/java/ch/so/agi/gretl/tasks/IliValidator.java#L50
https://github.com/sogis/gretl/blob/V2_4_x/gretl/src/main/java/ch/so/agi/gretl/tasks/IliValidator.java#L50

Die letzt Funktion (mit *.ngk.*) muss du glaub entfernen, da im 3er Branch diese Abhängigkeit noch fehlt.
