### ISSUE TITLE
Integrations-Test schlägt nach merge des Publisher-Branch fehl

### ISSUE THREAD

**Issue by ojeker** [sogis/gretl#72]
@claeis Verstehst du den Fehler?

![image](https://user-images.githubusercontent.com/24891004/176643240-57603b98-2912-4c0f-ba99-c8d900a70a80.png)

Die beiden Publisher-Tests schlagen beim test des Image fehl - siehe imageTest/index.html im beiliegenen zip.
[test_reports.zip](https://github.com/sogis/gretl/files/9018443/test_reports.zip)

**Comment by edigonzales** [comment]
"sogis/gretl" verwendet Gradle 5.1.1: https://github.com/sogis/gretl/blob/master/gradle/wrapper/gradle-wrapper.properties
Ins Dockerimage wird aber Gradle 4.2.1 gebrannt (die damals wohl aktuelle Version): https://github.com/sogis/gretl/blob/master/runtimeImage/gretl/Dockerfile

Fehlermeldung:
```
Caused by: java.lang.NoClassDefFoundError: org/gradle/api/provider/ListProperty
	at org.gradle.internal.reflect.ClassInspector.inspectClass(ClassInspector.java:72)
	at org.gradle.internal.reflect.ClassInspector.visitGraph(ClassInspector.java:56)
	at org.gradle.internal.reflect.ClassInspector.inspect(ClassInspector.java:36)
	at org.gradle.api.internal.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:283)
	at org.gradle.api.internal.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:238)
	at org.gradle.api.internal.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:110)
	... 97 more
Caused by: java.lang.ClassNotFoundException: org.gradle.api.provider.ListProperty
```

ListProperty erst ab 4.3: https://docs.gradle.org/current/javadoc/org/gradle/api/provider/ListProperty.html

Darum dürften wohl die Jar-Tests durchlaufen, die gleichen Tests mit Docker nicht. Man könnte wahrscheinlich problemlos auf 5.1.1 im Image updaten.

**Comment by edigonzales** [comment]
@ojeker @claeis Ich habe die Version im Image upgedatet. Jetzt erscheint ein neuer Fehler:

```
Info: ilivalidator-1.11.14-e147ed46900e545c1d99fdca44d652b0417a9cfb
Info: ili2c-5.2.6-6bef4c4d68a68f9fe4692aa5935cd575c9c40e14
Info: iox-ili-1.21.10-24089e0942222d5859690099ddadf929234d8628
Info: User <?>
Info: Start date 2022-07-08 08:21
Info: maxMemory 466432 KB
Info: dataFile </>
Error: java.io.FileNotFoundException: / (Is a directory)
Error:   / (Is a directory)
java.io.FileNotFoundException: / (Is a directory)
failed to run Publisher
java.lang.Exception: validation failed
	at ch.so.agi.gretl.steps.PublisherStep.publishFile(PublisherStep.java:399)
	at ch.so.agi.gretl.steps.PublisherStep.publishDatasetFromFile(PublisherStep.java:382)
	at ch.so.agi.gretl.tasks.Publisher.publishAll(Publisher.java:197)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
```

Das Problem sind die Verweise auf sourcePath und modeldir:

```

task publishFile(type: Publisher){
      dataIdent = "ch.so.agi.vermessung.edit"
      target = [project.buildDir]
      sourcePath = file("../../../../src/test/resources/data/publisher/files/av_test.itf")
      modeldir= file("../../../../src/test/resources/data/publisher/ili")
      //kgdiService=["http://localhost:8080/simi-svc/rest","admin","admin"]
}
```

Die zeigen auf ein Resources-Verzeichnis ausserhalb des Job-Verzeichnisses. Im Dockerimage ist aber nur das Job-Verzeichnis bekannt (weil das gemountet ist/wird).

Man könnte entweder die benötigten Daten statisch in das Job-Verzeichnis kopieren oder dynamisch vor dem Ausführen des eigentlichen Jobs mit Docker in der jeweilgen Java-Test-Methode.

**Comment by edigonzales** [comment]
https://github.com/sogis/gretl/commit/86027344542c080a53bc8f0783e75f57bce7b02d

Beim Regions-Int-Test bin ich nicht sicher wie robust er ist. Der Job ist erfolgreich, auch wenn glaub gar nichts gemacht wird. Festgestellt, weil ich zuerst einige Files nicht mitkopiert hatte.
